### ISSUE TITLE
ionic_v1 branch not detected with ionic cli 5.2.1

### ISSUE THREAD

**Issue by mluis** [OneSignalDevelopers/OneSignal-Ionic-Sample#14]
This project branch (ionic_v1) is not detected with the latest ionic's CLI 5.2.1

**Comment by jkasten2** [comment]
@mluis The `ionic_v1` branch in this repo is meant to work with version 1 of the Ionic frame. The CLI version support should be wider however it is possible a new version of Ionic CLI broke support.

Since Ionic Framework version 1 is quite old we don't plan to update the branch. However PRs are welcome if you want to contribute a fix for it.
